name: build nodejs Application - kishan
on: workflow_dispatch
jobs:
  job1: 
   runs-on: ubuntu-latest
   steps: 
    - name: Clone the repo 
      uses: actions/checkout@v4

    - name: list code
      run: ls -l
    - name: Install nodejs
      uses: actions/setup-node@v4
      with: 
          node-version: 18
          cache: 'npm'
    - name: Install dependencies 
      run: npm ci 
    - name: Executes test cases
      run: npm test
